feat: Add docs for query parsing & validation caching
mirumee/ariadne-website pull request #157
Opened 2023-08-02 13:22 UTC by lukapeschke

relates to https://github.com/mirumee/ariadne/issues/1101

2023-08-02 16:52 UTC, rafalp requested changes
Is this code verified to work in production? I am having some doubts about `lru_cache` being effective for `validate_query`.

2023-08-02 16:52 UTC, rafalp commented on docs/query-validation-caching.md
> +query parsing and validation.
Please don't break long lines manually.

2023-08-02 16:52 UTC, rafalp commented on docs/query-validation-caching.md
> +This can be done by providing a custom `query_parser` and `query_validator` to `GraphQL`.
```suggestion
This can be done by setting a custom `query_parser` and `query_validator` on your `GraphQL` server instance:
```

2023-08-02 16:52 UTC, rafalp commented on docs/query-validation-caching.md
> +```
```suggestion
```python
```

2023-08-02 16:52 UTC, rafalp commented on docs/query-validation-caching.md
> +    return cached_validator(schema=schema, document_ast=document_ast)
I don't think `DocumentNode` instances are hashable so they work with `lru_cache`?

2023-08-16 08:17 UTC, lukapeschke commented on docs/query-validation-caching.md
> +    return cached_validator(schema=schema, document_ast=document_ast)
Yes, they are hashable:
```python
>>> from graphql import parse

>>> hash(parse('query { a(b: String) { x } }'))
-8564336626102477568
```

2023-09-07 16:04 UTC, lukapeschke commented
@rafalp does the updated version LGTY ?

2023-09-07 16:18 UTC, rafalp commented
Hello, apologies - I've forgotten about this PR completely 😅

The code looks good but I have two nitpicks:

- Documents title should mention caching for both query parsing and validation (but I have to suggestion for this ATM)
- Initial paragraph should explain that enabling cache may improve server's performance.

2023-09-07 16:24 UTC, rafalp reviewed
Added suggestion for initial paragraph

2023-09-07 16:24 UTC, rafalp commented on docs/query-validation-caching.md
> +In case you are serving complex queries, or a lot of identical queries, it might make sense for you to cache the query parsing and validation.
```suggestion
Query parsing and validation steps can be extended with custom code adding an extra caching step, which in some situations can greatly improve server's speed at cost of greater memory usage.
```

2023-09-08 08:38 UTC, lukapeschke commented
@rafalp no problem :smile: let me know what you think about the latest version

2024-01-10 10:35 UTC, lukapeschke commented
@rafalp can we merge or close this ? I'm trying to get on top of all my open PRs :sweat_smile:

2024-01-10 17:43 UTC, rafalp approved these changes

2024-01-10 17:46 UTC, merged

2024-01-10 17:46 UTC, rafalp commented
@lukapeschke I'm happy to merge this documentation now and improve it later myself. Thanks!

2024-01-11 08:35 UTC, lukapeschke commented
Great, thank you!