GraphQL over SSE documentation
mirumee/ariadne-website pull request #185
Opened 2024-12-20 19:03 UTC by danplischke

Documentation for mirumee/ariadne#1195

2025-01-09 21:27 UTC, rafalp requested changes
Please remove all hard linebreaks from the markdown paragraphs so they won't get parsed into `<br />` by docusaurus.

2025-01-09 21:27 UTC, rafalp commented on docs/subscriptions.md
> +## Using Server-Sent Events Protocol
We are using double blank line between headers for visual separation in markdown too:

```suggestion

## Using Server-Sent Events Protocol
```

2025-01-09 21:27 UTC, rafalp commented on docs/subscriptions.md
> +In addition to subscriptions over WebSockets, Ariadne also allows an alternative subscriptions approach, `graphql-sse`,
This should be reworded and hard linebreak removed:

```
Instead of WebSockets, [Server-Sent Events (SSE)](https://github.com/enisdenjo/graphql-sse/blob/master/PROTOCOL.md) can be used as a transmission protocol for subscriptions. This approach uses single, long-lived HTTP connection to push data to clients.
```

2025-01-09 21:27 UTC, rafalp commented on docs/subscriptions.md
> +a `ariadne.contrib.sse.GraphQLHTTPSSEHandler` instance:
```suggestion
an `ariadne.contrib.sse.GraphQLHTTPSSEHandler` instance:
```

2025-01-09 21:27 UTC, rafalp commented on docs/subscriptions.md
> +> The `GraphQLHTTPSSEHandler` only supports asynchronous servers, due to the nature of subscriptions.
```suggestion
> The `GraphQLHTTPSSEHandler` requires the ASGI server to work.
```

2025-01-11 20:45 UTC, danplischke commented
Thanks for the feedback @rafalp! Everything has been included in the recent commit.

2025-01-29 19:04 UTC, rafalp commented on docs/subscriptions.md
> +from typing import Any, AsyncGenerator
```suggestion
from typing import Any, AsyncGenerator

```

2025-01-29 19:05 UTC, rafalp commented on docs/subscriptions.md
> +Subscriptions can be consumed using the [graphql-sse](https://github.com/enisdenjo/graphql-sse/) JavaScript client library or any other compatible implementation.
```suggestion
SSE subscriptions can be consumed using the [graphql-sse](https://github.com/enisdenjo/graphql-sse/) JavaScript client library or any other compatible implementation.
```

2025-01-29 19:05 UTC, rafalp commented on docs/subscriptions.md
> +> This handler only supports the `distinct connections mode` mode of the protocol due to Ariadne's stateless implementation.
```suggestion
> This handler only supports the `distinct connections` mode of the protocol due to Ariadne's stateless implementation.
```

2025-01-29 19:06 UTC, rafalp approved these changes

2025-01-29 21:33 UTC, merged